[Flex] Added `Flex` Component
cepave-f2e/vue-owl-ui pull request #100
Opened 2016-12-30 09:24 UTC by rwu823

![image](https://cloud.githubusercontent.com/assets/890063/21562574/f7debd3c-cecd-11e6-8279-1c8de728b022.png)

2016-12-30 09:27 UTC, rwu823 commented on src/client/views/flex/index.js
> +          { [...Array(6)].map((v, i) => {
神 code 乍現 QQ

2016-12-30 09:32 UTC, chuanxd commented on src/client/views/flex/index.js
> +          { [...Array(6)].map((v, i) => {
XD

2017-01-04 03:34 UTC, chuanxd commented on src/components/flex/flex.scss
> +  justify-content: center;
這真的很方便

2017-01-04 03:40 UTC, rwu823 commented on src/components/flex/flex.scss
> +      margin-right: 0!important;
這邊 `!important` 是必備，先講一下 QQ

2017-01-04 03:43 UTC, CApopsicle commented on src/components/flex/flex.scss
> +  justify-content: center;
對呀這我也很常用

2017-01-04 04:00 UTC, chuanxd requested changes

2017-01-04 04:00 UTC, chuanxd commented on src/client/views/flex/flex.scss
> +  background: lighten(#590AAA, 50%);
lowercase `#590aaa` 我們統一用小寫

2017-01-04 04:00 UTC, chuanxd commented on src/components/flex/flex.scss
> +      margin-right: 0!important;
ok
space QQ
`margin-right: 0 !important;`

2017-01-04 04:00 UTC, chuanxd commented on src/client/views/flex/doc.md
> +Set the margin of each column, default is `20`.
說明加上單位會不會比較清楚呢？ `px`

2017-01-04 04:00 UTC, chuanxd commented on src/components/flex/index.js
> +        styleObj.flex = 1
這邊直接做等分嗎？
如果像是測試裡面的這段
```jsx
<Flex>
  <Flex.Col size="2" />
  <Flex.Col size="auto" />
</Flex>
```

render 後 column 會都為 `6` ?

2017-01-04 04:02 UTC, rwu823 commented on src/components/flex/index.js
> +        styleObj.flex = 1
If in 12 grids set `2` and `auto` it should be rendered as `2` and `10`

2017-01-04 04:03 UTC, rwu823 commented on src/components/flex/index.js
> +        styleObj.flex = 1
`auto` is mean automate flexible

2017-01-04 04:05 UTC, rwu823 commented on src/components/flex/index.js
> +        styleObj.flex = 1
`auto * 2` it'll be `6` `6`     

`auto * 3` it'll be `4` `4` `4`

2017-01-04 04:07 UTC, rwu823 commented on src/client/views/flex/flex.scss
> +  background: lighten(#590AAA, 50%);
why no exception in stylelint QQ

2017-01-04 04:07 UTC, chuanxd commented on src/components/flex/index.js
> +        styleObj.flex = 1
got it.

2017-01-04 04:12 UTC, chuanxd commented on src/client/views/flex/flex.scss
> +  background: lighten(#590AAA, 50%);
https://github.com/cepave-f2e/vue-owl-ui/blob/dev/.stylelintrc.js#L5

I had set.

2017-01-04 04:14 UTC, chuanxd commented on src/client/views/flex/flex.scss
> +  background: lighten(#590AAA, 50%);
@rwu823 CI lint missing ?

2017-01-04 08:18 UTC, rwu823 commented
All suggestions are fixed

2017-01-04 08:18 UTC, merged

2017-01-04 09:15 UTC, chuanxd commented
自動被忽略了QQ