WIP: [MultiSelect] <MultiSelect /> component
cepave-f2e/vue-owl-ui pull request #127
Opened 2017-02-08 10:28 UTC by CApopsicle

http://jira.cepave.com/browse/OWL-1474

![multiselect](https://cloud.githubusercontent.com/assets/5334755/22733347/594f4168-ee2c-11e6-8b61-a759b5c2b810.gif)

- [x] component
- [x] doc
- [x] test specs

2017-02-09 09:30 UTC, CApopsicle commented
- 不確定是不是要做遠程搜索(像graph搜尋監控項) 但先加入 props `loading`
- keyBoardEvent無法測試QQ

2017-02-09 12:27 UTC, rwu823 commented on src/components/multi-select/index.js
> +    this.displayIdx = [...Array(this.options.length)].map((v, i) => {
😘

2017-02-13 07:12 UTC, CApopsicle commented on src/components/multi-select/index.js
> +    this.displayIdx = [...Array(this.options.length)].map((v, i) => {
😊

2017-02-13 10:25 UTC, rwu823 commented
![remove_labels](https://cloud.githubusercontent.com/assets/890063/22879586/bb688a62-f219-11e6-8301-40717f9c0194.gif)

remove 最後一個 label 時好像怪怪的，需要點二次？

2017-02-13 10:28 UTC, rwu823 commented
![input_height](https://cloud.githubusercontent.com/assets/890063/22879705/33497c80-f21a-11e6-9365-b2a0f178936b.gif)


有 label 與無label的情況，input 高度不該變動 (視覺上容易不舒服)

2017-02-13 10:33 UTC, rwu823 commented
![labels_sort](https://cloud.githubusercontent.com/assets/890063/22879833/ccf73c64-f21a-11e6-8b51-143b37687e68.gif)

新加的 label 應該是放最後面，無需再排序，不然視覺上也會跳動

2017-02-13 10:40 UTC, rwu823 commented
![hover_focus](https://cloud.githubusercontent.com/assets/890063/22880014/7868a6dc-f21b-11e6-9b5e-0f33fc70d421.gif)

mouse hover 與上下鍵移動的 index 記錄要一致:

### Steps to reproduce
`mousehover`  到 `index 5` 的 list 上，按上下鍵還是從 1 開始計算

### What is Expected?
`mousehover`  到 `index 5` 的 list 上，按上鍵回到 4，按下鍵接到 6

2017-02-14 07:54 UTC, CApopsicle commented
- 固定input高度`fixed`
- 新加的label放在最後`fixed`

- 點兩次才關掉最後一個label好像是因為沒點到label，而是點到label跟外匡中間，讓隱形的input `onBlur` 了

- mouse hover 與上下鍵移動的 index 記錄要一致: 嘗試中QQ 
已經成功讓使用者使用鍵盤的時候用`pointer-events: none`不讓mouse event被偵測到、再度mouse move的時候恢復偵測mouse event，但找不到好方法取消gif裡面hover在`caterpie`上造成的style改變

![multiselect-3](https://cloud.githubusercontent.com/assets/5334755/22919668/08b9ccb0-f2cc-11e6-8e1e-783797ad934f.gif)

2017-02-15 06:51 UTC, CApopsicle commented
@rwu823 all fixed

2017-02-15 07:16 UTC, rwu823 commented
> http://element.eleme.io/#/en-US/component/select

還有一項功能是按 `backspace` 時的刪除功能:

- 如果當下沒有字會 focus 最後一個 label，再按一次則刪除

2017-02-15 07:18 UTC, rwu823 requested changes

2017-02-15 07:18 UTC, rwu823 commented on src/components/multi-select/index.js
> +        if (newVal[displayKey].toLowerCase().includes(this.$refs.searchField.value.toLowerCase())) {
`const searchField = this.$refs.searchField.value.trim()` 

兩邊比對前都把前後空白濾掉比較好，防止用戶一開始按到 `space` 就沒資料

2017-02-16 03:23 UTC, CApopsicle commented on src/components/multi-select/index.js
> +        if (newVal[displayKey].toLowerCase().includes(this.$refs.searchField.value.toLowerCase())) {
fixed!

2017-02-16 03:24 UTC, CApopsicle commented
按 `backspace` 時的刪除功能

![multiselect-4](https://cloud.githubusercontent.com/assets/5334755/23006016/65e5e4fe-f43a-11e6-97bd-b83946d81607.gif)

2017-02-16 06:31 UTC, chuanxd commented on src/components/multi-select/index.js
> +    this.displayIdx = [...Array(this.options.length)].map((v, i) => {
👀

2017-02-16 08:44 UTC, rwu823 commented on src/components/multi-select/index.js
> +        style[s.disablePointer] = (disablePointer) ? true : false
兩個 tips

-  這邊可以集合進來，就不用每次寫 `style[]`:
```js
const style = {
  [s.options]: true,
  [s.selected]: (isSelected >= 0),
  [s.focused]: (idx === this.focusedIdx)
}
```
- `(isSelected >= 0) ? true : false` === `(isSelected >= 0)` 兩式相等， `true : false` 其實不用寫出來也一樣，被比較完的式子也是 `true` or `false`

2017-02-16 08:46 UTC, rwu823 commented on src/components/multi-select/index.js
> +        style[s.disablePointer] = (disablePointer) ? true : false
☝🏻 可以讓 code 更乾淨

2017-02-16 08:50 UTC, rwu823 commented on src/components/multi-select/index.js
> +        style[s.disablePointer] = (disablePointer) ? true : false
然後這邊是組成多個 `class name`，變數名取複數形式 `classes`，會較 `style` 明確

2017-02-16 08:53 UTC, rwu823 requested changes

2017-02-16 08:53 UTC, rwu823 commented on src/components/multi-select/index.js
> +      const _loadingOption = <div class={[s.loadingOption]}><Loading typ="pie" size={10} class={[s.loading]} />loading...</div>
文字檔可拉出為 `props`，讓 user 可使用多語

2017-02-16 08:55 UTC, rwu823 requested changes

2017-02-16 08:55 UTC, rwu823 commented on src/components/multi-select/index.js
> +      style[s.disabled] = disable
同上述，可直接用 es6 寫法:

2017-02-16 09:58 UTC, CApopsicle commented on src/components/multi-select/index.js
> +        style[s.disablePointer] = (disablePointer) ? true : false
OK! 🍒  fixed!

2017-02-16 09:59 UTC, CApopsicle commented on src/components/multi-select/index.js
> +      const _loadingOption = <div class={[s.loadingOption]}><Loading typ="pie" size={10} class={[s.loading]} />loading...</div>
fixed! 新增 `loadingMsg`

2017-02-16 09:59 UTC, CApopsicle commented on src/components/multi-select/index.js
> +      style[s.disabled] = disable
fixed

2017-02-23 03:08 UTC, CApopsicle commented
@rwu823 all fixed!

2017-02-23 03:37 UTC, rwu823 approved these changes

2017-02-23 03:37 UTC, merged