[OWL-1101] <Loading /> doc
cepave-f2e/vue-owl-ui pull request #13
Opened 2016-10-05 07:47 UTC by CApopsicle

document of component <Loading/>
http://jira.cepave.com/browse/OWL-1101

2016-10-05 08:52 UTC, rwu823 requested changes

2016-10-05 08:52 UTC, rwu823 commented on src/client/views/loading/index.js
> +        <Markdown src={require('./loading.md')} opts={{ codeTheme: 'light' }} />
`opts={{ codeTheme: 'light' }}` 可以不用加

2016-10-05 08:56 UTC, CApopsicle commented on src/client/views/loading/index.js
> +        <Markdown src={require('./loading.md')} opts={{ codeTheme: 'light' }} />
OK!

2016-10-06 07:01 UTC, chuanxd requested changes

2016-10-06 07:01 UTC, chuanxd commented on src/client/views/loading/index.js
> +module.exports = loading
Upper case

2016-10-06 07:50 UTC, rwu823 requested changes

2016-10-06 07:50 UTC, rwu823 commented on src/client/views/loading/index.js
> +module.exports = loading
可以用 `LoadingPage` 來命名

2016-10-07 02:42 UTC, CApopsicle commented on src/client/views/loading/index.js
> +module.exports = loading
OK! 已修改

2016-10-07 02:49 UTC, chuanxd requested changes

2016-10-07 02:49 UTC, chuanxd commented on src/client/views/loading/loading.md
> +## Demo
?? where is ur DEMO code?

2016-10-07 02:53 UTC, CApopsicle commented on src/client/views/loading/loading.md
> +## Demo
在 `src/client/views/loading/index.js` 裡面啊

2016-10-07 02:56 UTC, chuanxd commented on src/client/views/loading/loading.md
> +## Demo
:ok_man:

2016-10-07 02:58 UTC, chuanxd commented
左邊 side bar 沒有加上 router ?

2016-10-07 03:37 UTC, CApopsicle commented
@chuanxd 加上了

2016-10-07 03:40 UTC, chuanxd approved these changes

2016-10-07 03:40 UTC, chuanxd commented
LGTM

2016-10-07 03:40 UTC, chuanxd commented
rebase dev

2016-10-07 09:30 UTC, CApopsicle commented
Rebase了!

2016-10-07 14:04 UTC, rwu823 requested changes

2016-10-07 14:04 UTC, rwu823 commented on src/client/app.js
> +                <router-link to="./loading">Loading</router-link>
`/loading` 這樣比較好，如果未來層級數不同才不會導致連錯，也與 routes 批配

2016-10-11 02:47 UTC, CApopsicle commented on src/client/app.js
> +                <router-link to="./loading">Loading</router-link>
OK! 修改了!

2016-10-11 03:06 UTC, rwu823 approved these changes

2016-10-11 03:08 UTC, merged