Select component
cepave-f2e/vue-owl-ui pull request #16
Opened 2016-10-11 02:09 UTC by chuanxd

### What? Why?

- [x] `<Select />` component. 
- [x] testing
- [ ] Document

### How was it tested?
localhost

![image](https://cloud.githubusercontent.com/assets/4191668/19256515/44595122-8f9a-11e6-8ace-939aec19fb2d.png)

cc @rwu823 @CApopsicle

2016-10-13 03:39 UTC, rwu823 requested changes

2016-10-13 03:39 UTC, rwu823 commented on src/components/select/__test__/select.spec.js
> +  vm.$el.dispatchEvent(blurEvent)
已經引入 `cash-dom` 我們改用 jQuery 方式來精寫 trigger 吧

2016-10-13 07:39 UTC, chuanxd commented on src/components/select/__test__/select.spec.js
> +  vm.$el.dispatchEvent(blurEvent)
fixed

2016-10-24 09:25 UTC, rwu823 commented
我接手囉，來找 `data-*` 不見的原因 QQ

2016-11-04 02:24 UTC, chuanxd commented on src/components/select/__test__/select.spec.js
> +  expect(vm.d.selectedIdx === +optionItem.getAttribute('data-idx')).toBe(true)
code 被改光光QQ

2016-11-17 20:40 UTC, rwu823 approved these changes

2016-11-18 10:01 UTC, CApopsicle commented on src/components/select/index.js
> +          <div class={[]} data-role="select-option" data-idx={i}>
class QQ

2016-11-18 10:23 UTC, chuanxd commented
console 有錯誤

2016-11-21 00:33 UTC, rwu823 commented
有錯誤是 `/home` 的 `<Select />` @@?

2016-11-21 02:27 UTC, CApopsicle commented
對耶 是 `/home` 的

2016-11-21 02:39 UTC, chuanxd commented
= ="" ..

2016-11-21 02:49 UTC, rwu823 commented on src/components/select/index.js
> +          <div class={[]} data-role="select-option" data-idx={i}>
fixed QQ

2016-11-21 02:51 UTC, chuanxd commented on src/components/select/index.js
> +        <input type="hidden" name={name} value={value}/>
`<input type="hidden" name={name} value={value} />`

有沒有 eslint 可以用？QQ

2016-11-21 08:07 UTC, chuanxd commented on src/client/views/select/index.js
> +        <Select {...{ props: selectProps }} onchange={selectOnChange} />
link babel-plugin-transform-vue-jsx issue 37
https://github.com/vuejs/babel-plugin-transform-vue-jsx/issues/37

2016-11-21 08:11 UTC, merged