Vue.v2 checkbox
cepave-f2e/vue-owl-ui pull request #22
Opened 2016-10-17 03:34 UTC by CApopsicle

Checkbox component 
http://jira.cepave.com/browse/OWL-941

- [x] <Checkbox /> component
- [x] Test Specs
- [x] Document

2016-10-18 06:29 UTC, CApopsicle commented
Markdown component裡，若使用 `# checkbox` ，會產生 `<a href="#checkbox>` ，使得同頁也名為checkbox的icon `<Icon typ="checkbox"/>` (後被轉為 `<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#checkbox"></use>` ) 失效

2016-10-18 06:32 UTC, chuanxd commented
找這個問題找好久...

2016-10-20 07:12 UTC, rwu823 requested changes

2016-10-20 07:12 UTC, rwu823 commented on src/components/checkbox/__test__/checkbox.spec.js
> +    expect(data).toEqual({ 1 : false })
`:` 前多了 space QQ

2016-10-20 07:12 UTC, rwu823 commented on src/components/checkbox/__test__/checkbox.spec.js
> +    expect(data).toEqual({ all : false, 1 : false, 2 : true })
同上，分號格式

2016-10-20 08:00 UTC, CApopsicle commented on src/components/checkbox/__test__/checkbox.spec.js
> +    expect(data).toEqual({ 1 : false })
OK!已修改!

2016-10-20 08:00 UTC, CApopsicle commented on src/components/checkbox/__test__/checkbox.spec.js
> +    expect(data).toEqual({ all : false, 1 : false, 2 : true })
OK!已修改!

2016-10-20 08:33 UTC, merged