[OWL-1072] add test cases without `onChange`
cepave-f2e/vue-owl-ui pull request #26
Opened 2016-10-19 07:57 UTC by CApopsicle

新增test specs: `test the condition without onChange`, :arrow_up: branch coverage

2016-10-20 07:17 UTC, rwu823 commented on src/components/switch/__test__/switch.spec.js
> +  expect(vm.check).toBe(false)
這邊不太懂， spec 是 without `onChange` 但卻要觸發 `handleClick`

2016-10-20 09:05 UTC, CApopsicle commented on src/components/switch/__test__/switch.spec.js
> +  expect(vm.check).toBe(false)
因為
```
if (onChange) {
   onChange(data)
}
```
在`handleClick()`裡面
像是這隻檔案裡面的第一個spec，我沒有給component onChange的props ，所以會使得branch coverage只有50%，因為沒跑到這一段
```
if (onChange) {
   onChange(data)
}
```

2016-10-20 09:05 UTC, CApopsicle commented on src/components/switch/__test__/switch.spec.js
> +  expect(vm.check).toBe(false)
但是我發現單純觸發click事件或是直接用handleClick()，不需要$nextTick才能改變其他data ，等會把它拿掉

2016-10-20 12:02 UTC, chuanxd approved these changes
LGTM

2016-10-24 03:19 UTC, CApopsicle commented
Rebased!

2016-10-24 06:40 UTC, rwu823 requested changes

2016-10-24 06:40 UTC, rwu823 commented on src/components/switch/__test__/switch.spec.js
>    vm.handleClick()
在測試裡應該盡量避免直接呼叫 component methods (除了 props 外的東西應該都是不希望被外部呼叫的)， 改用 dom trigger 來呼叫，好處是如果 `on-click` typo 能測的出來

2016-10-24 06:40 UTC, rwu823 commented on src/components/switch/__test__/switch.spec.js
> +  vm.handleClick()
同上

2016-10-24 06:42 UTC, chuanxd commented on src/components/switch/__test__/switch.spec.js
>    vm.handleClick()
學習惹

2016-10-24 07:24 UTC, CApopsicle commented on src/components/switch/__test__/switch.spec.js
>    vm.handleClick()
OK! 已改!

2016-10-24 07:25 UTC, CApopsicle commented on src/components/switch/__test__/switch.spec.js
> +  vm.handleClick()
OK! 已改!

2016-10-24 07:27 UTC, rwu823 approved these changes

2016-10-24 07:34 UTC, merged