Update jest configuration
cepave-f2e/vue-owl-ui pull request #29
Opened 2016-10-20 12:54 UTC by chuanxd

### What? Why?
  - add `collectCoverageFrom`

![image](https://cloud.githubusercontent.com/assets/4191668/19560491/540c5d2a-9707-11e6-9afc-304e6d723293.png)

### How was it tested?
npm run test

cc @rwu823 @CApopsicle

2016-10-20 21:20 UTC, rwu823 commented on package.json
> +      "**/src/components/**/*.{js,jsx}",
`**/src/components/**/index.js` 只要 check 這隻 main file 就好了，match 速度會較快

2016-10-20 21:21 UTC, rwu823 commented
Well done

2016-10-20 21:30 UTC, rwu823 requested changes

2016-10-20 21:30 UTC, rwu823 commented on package.json
> +      "!**/src/components/index.js"
用上面寫法可以不用這行

2016-10-21 05:46 UTC, chuanxd commented on package.json
> +      "**/src/components/**/*.{js,jsx}",
@rwu823 

我本來是這樣寫，但是會錯

<details>
```sh
Running coverage on untested files...
              Failed to collect coverage from /Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/src/components/index.js
              ERROR: Error: /Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/src/components/index.js: Can't resolve '~dist/owl-ui.css' in '/Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/src/components'
              STACK: Error: /Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/src/components/index.js: Can't resolve '~dist/owl-ui.css' in '/Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/src/components'
    at onResolved (/Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/node_modules/enhanced-resolve/lib/Resolver.js:66:16)
    at loggingCallbackWrapper (/Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/node_modules/tapable/lib/Tapable.js:108:46)
    at innerCallback (/Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/node_modules/tapable/lib/Tapable.js:210:15
    at innerCallback (/Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
    at loggingCallbackWrapper (/Users/chuanxd/Documents/cepave/workspace/vue-owl-ui/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
```
</details>

`/src/components/index.js`

```js
const isNode = !(typeof window !== 'undefined' && window.document && document.createElement)

if (process.env.NODE_ENV === 'build' && !isNode) {
  const style = document.createElement('style')
  style.textContent = require('raw!~dist/owl-ui.css')

  document.head.appendChild(style)
}

module.exports = {
  Select: require('./select')
}
```

2016-10-21 06:17 UTC, rwu823 approved these changes

2016-10-21 06:18 UTC, merged