Vue.v2 switch button
cepave-f2e/vue-owl-ui pull request #3
Opened 2016-09-21 06:54 UTC by CApopsicle

making switch button component
http://jira.cepave.com/browse/OWL-1072

2016-09-23 05:53 UTC, chuanxd requested changes
please follow #5

2016-10-03 06:26 UTC, CApopsicle commented
@chuanxd 這個component修好了喔!

2016-10-03 07:26 UTC, rwu823 requested changes

2016-10-03 07:26 UTC, rwu823 commented on src/components/switch/index.js
> +          <label class={[s._toggle]} on-click={handleClick}></label>
Change `s._toggle` to `s.toggle`

2016-10-03 07:26 UTC, rwu823 commented on src/components/switch/index.js
> +        [name]: this.check
Where is `name` variable?

2016-10-03 07:33 UTC, rwu823 commented on src/components/switch/__test__/switch.spec.js
> +    expect(Object.values(data)[0]).toBe(false)
這一條 spec 要改，應該要拿 `name` 來測

2016-10-03 07:35 UTC, rwu823 commented on src/components/switch/__test__/switch.spec.js
> +    expect(Object.values(data)[0]).toBe(false)
這一條 spec 要改，應該要拿 `name` 來測

2016-10-03 07:35 UTC, rwu823 requested changes

2016-10-03 07:35 UTC, rwu823 commented on src/components/switch/__test__/switch.spec.js
> +    expect(Object.values(data)[0]).toBe(false)
這一條 spec 要改，應該要拿 `name` 來測

2016-10-04 02:27 UTC, CApopsicle commented on src/components/switch/index.js
> +          <label class={[s._toggle]} on-click={handleClick}></label>
OK! 已修改

2016-10-04 02:27 UTC, CApopsicle commented on src/components/switch/__test__/switch.spec.js
> +    expect(Object.values(data)[0]).toBe(false)
OK! 已修改

2016-10-04 02:29 UTC, CApopsicle commented on src/components/switch/index.js
> +        [name]: this.check
name 應該是 props
已include進來 `const { name } = this`

2016-10-05 08:21 UTC, CApopsicle commented
@rwu823 @chuanxd 這個component修改好嘍！

2016-10-05 08:23 UTC, chuanxd approved these changes

2016-10-05 08:23 UTC, chuanxd requested changes
rebase branch `dev` please

2016-10-05 09:04 UTC, rwu823 approved these changes

2016-10-05 09:04 UTC, rwu823 commented on src/components/switch/__test__/switch.spec.js
> +    expect(Object.values(data)[0]).toBe(false)
這樣`expect`會更直覺
```js
expect(data).toEqual({test: false})
```

2016-10-05 09:16 UTC, CApopsicle commented on src/components/switch/__test__/switch.spec.js
> +    expect(Object.values(data)[0]).toBe(false)
OK!已修改

2016-10-07 02:52 UTC, chuanxd approved these changes

2016-10-07 02:52 UTC, merged