[OWL-1169] <Input> component
cepave-f2e/vue-owl-ui pull request #33
Opened 2016-10-24 09:32 UTC by CApopsicle

Input Component
http://jira.cepave.com/browse/OWL-1169

現在設計成從外部這樣拿input值 :`this.$refs.testRef.value`
```
<Input icon={['grid-4', '#e6175c']} name="test" ref="testRef"/>
```

- [x] Input Component
- [ ] Test specs
- [ ] Doc

2016-11-01 09:20 UTC, chuanxd commented
來個圖吧 😍

2016-11-01 09:28 UTC, CApopsicle commented
![2016-11-01 5 27 34](https://cloud.githubusercontent.com/assets/5334755/19885245/8bb9eff8-a058-11e6-9c0b-7386318e285d.png)

2016-11-01 09:49 UTC, rwu823 commented
沒什問題，再補上 `password` 功能吧

2016-11-01 09:50 UTC, rwu823 commented
@CApopsicle  愈寫愈好了 QQ

2016-11-01 10:00 UTC, chuanxd commented
👍

2016-11-03 03:18 UTC, CApopsicle commented
補上 `password`  和 `x` 了！

2016-11-03 03:20 UTC, CApopsicle commented
補上 `password`  和 `x` 了！
@rwu823 @chuanxd

2016-11-07 07:31 UTC, CApopsicle commented
- 新增從外部得知按下  `x` 的功能及文件
- 新增從外部綁定 `on-keypress` 的文件

2016-11-07 07:45 UTC, rwu823 approved these changes

2016-11-07 07:45 UTC, rwu823 commented on src/components/input/index.js
> +          ? <span on-click={handleIconClick}><Icon typ={icon[0]} fill={icon[1]} class={[s.icon]}/></span>
`</span>` is needless

2016-11-07 07:45 UTC, rwu823 commented on src/components/input/index.js
> +          ? <span on-click={handlePwdStyle}><Icon typ="eye" fill={pwdFill} class={[s.icon]}/></span>
`</span>` is needless

2016-11-07 07:45 UTC, rwu823 commented on src/components/input/index.js
> +        }
兩邊 `input` 幾乎一樣，只差在 `type` 應該不需要判斷了？

2016-11-07 07:46 UTC, rwu823 requested changes
request changes

2016-11-07 07:48 UTC, chuanxd commented on src/components/input/index.js
> +          ? <span on-click={handlePwdStyle}><Icon typ="eye" fill={pwdFill} class={[s.icon]}/></span>
@rwu823 self close ?

2016-11-07 07:50 UTC, chuanxd commented on src/components/input/index.js
> +          ? <span on-click={handleIconClick}><Icon typ={icon[0]} fill={icon[1]} class={[s.icon]}/></span>
self close ?

2016-11-07 07:53 UTC, rwu823 commented on src/components/input/index.js
> +          ? <span on-click={handlePwdStyle}><Icon typ="eye" fill={pwdFill} class={[s.icon]}/></span>
@CApopsicle  @chuanxd  喔喔 看錯了

2016-11-07 07:54 UTC, rwu823 commented on src/components/input/index.js
> +          ? <span on-click={handleIconClick}><Icon typ={icon[0]} fill={icon[1]} class={[s.icon]}/></span>
@CApopsicle @chuanxd 喔喔 看錯了

2016-11-07 07:59 UTC, CApopsicle commented on src/components/input/index.js
> +        }
type 是因為 
![2016-11-07 3 55 46](https://cloud.githubusercontent.com/assets/5334755/20050207/dc3cd87e-a502-11e6-8533-915f391ec79d.png)
他需要default是出現● ● ●

2016-11-07 09:20 UTC, CApopsicle commented
<Input/> with `x` 已改為有input value時才會出現 `x` 
@rwu823 @chuanxd

2016-11-07 09:45 UTC, CApopsicle commented
Input with `x` 已修改為有input value時才會出現 `x`
@rwu823 @chuanxd 
![e1to4jn2qj](https://cloud.githubusercontent.com/assets/5334755/20053076/dd5d81cc-a511-11e6-8aa5-7b1ae6571f86.gif)

2016-11-08 02:11 UTC, CApopsicle commented
改個icon位置 垂直置中 :laughing::laughing:

2016-11-08 02:15 UTC, chuanxd requested changes

2016-11-08 02:15 UTC, chuanxd commented on src/client/views/input/input.scss
> +.wrapper{
為了好閱讀，我們習慣會在左大刮號前加上一個空白。

2016-11-08 02:23 UTC, rwu823 commented on src/client/views/input/input.scss
> +.wrapper{
徵求 lint QQ

2016-11-08 02:25 UTC, CApopsicle commented on src/client/views/input/input.scss
> +.wrapper{
改了! :satisfied:

2016-11-08 02:26 UTC, rwu823 commented on src/client/views/input/input.scss
> +.wrapper{
還有這個的 lint:

``` jsx
// bad:
<input/>

// good
<input />
```

2016-11-08 02:35 UTC, chuanxd commented on src/client/views/input/input.scss
> +.wrapper{
@CApopsicle ☝️

2016-11-08 02:38 UTC, CApopsicle commented
已加stylelint

2016-11-08 03:02 UTC, CApopsicle commented
scss的大括號和self-closing前的空白改好了

2016-11-08 09:17 UTC, CApopsicle commented
終於整理完commit了:sweat::sweat:
@rwu823 @chuanxd

2016-11-09 03:25 UTC, rwu823 approved these changes

2016-11-09 03:50 UTC, chuanxd approved these changes

2016-11-09 03:50 UTC, chuanxd commented
LGTM

2016-11-09 03:51 UTC, merged