[OWL-1071] <DualListBox /> component
cepave-f2e/vue-owl-ui pull request #46
Opened 2016-11-16 03:44 UTC by CApopsicle

DualListBox component
http://jira.cepave.com/browse/OWL-1071

![duallistbox](https://cloud.githubusercontent.com/assets/5334755/20334011/bd827c5e-abf1-11e6-93ae-9e46a58f6dbf.gif)

- [x] component
- [x] test specs
- [x] doc

2016-11-16 06:45 UTC, chuanxd commented
讚讚

2016-11-21 08:35 UTC, rwu823 requested changes

2016-11-21 08:35 UTC, rwu823 commented on src/components/dualListbox/__test__/duallistbox.spec.js
> +  const hostGroup = {
測試數據建議可以用簡單，可讀性高一點的方便維護 QQ

2016-11-21 08:37 UTC, chuanxd requested changes

2016-11-21 08:37 UTC, chuanxd commented on src/components/dualListbox/__test__/duallistbox.spec.js
> +  const hostGroup = {
這數據要拿掉QQ

2016-11-21 08:38 UTC, rwu823 requested changes

2016-11-21 08:38 UTC, rwu823 commented on src/client/views/duallistbox/doc.md
> +  data: {
props `data` 易跟 vue 裡的 data 搞混，建議換名

2016-11-21 08:38 UTC, rwu823 commented on src/client/views/duallistbox/index.js
> +        <Dual.Group data={labels} class={[s.dualGroup]} onChange={this.getDualData}/>
掃 eslint

2016-11-21 08:40 UTC, rwu823 requested changes

2016-11-21 08:40 UTC, rwu823 commented on src/client/views/duallistbox/doc.md
> +  onChange: {
`onChange` QQ

2016-11-21 09:13 UTC, CApopsicle commented on src/client/views/duallistbox/doc.md
> +  data: {
有沒有建議的命名ＱＱ

2016-11-21 09:14 UTC, CApopsicle commented on src/client/views/duallistbox/index.js
> +        <Dual.Group data={labels} class={[s.dualGroup]} onChange={this.getDualData}/>
👌

2016-11-21 09:14 UTC, CApopsicle commented on src/client/views/duallistbox/doc.md
> +  onChange: {
👌

2016-11-21 09:41 UTC, chuanxd commented on src/client/views/duallistbox/doc.md
> +  data: {
`items` or `options` ?

2016-11-22 02:17 UTC, CApopsicle commented on src/components/dualListbox/__test__/duallistbox.spec.js
> +  const hostGroup = {
修改了！

2016-11-22 02:19 UTC, CApopsicle commented on src/client/views/duallistbox/doc.md
> +  data: {
修改了！變成 左：`items` 和 右：`selectedItems`

2016-11-22 02:20 UTC, CApopsicle commented on src/client/views/duallistbox/doc.md
> +  onChange: {
修改了！

2016-11-22 06:26 UTC, chuanxd requested changes

2016-11-22 06:26 UTC, chuanxd commented on src/components/dualListbox/__test__/duallistbox.spec.js
> +    // console.log(data);
??

2016-11-22 06:27 UTC, CApopsicle commented on src/client/views/duallistbox/doc.md
> +  onChange: {
已修改！改成用`$emit` 和`onChange`了

2016-11-22 06:29 UTC, chuanxd requested changes

2016-11-22 06:29 UTC, chuanxd commented on src/client/views/duallistbox/index.js
> +      console.log(data)
??

2016-11-22 06:30 UTC, CApopsicle commented on src/components/dualListbox/__test__/duallistbox.spec.js
> +    // console.log(data);
想說裡面不知道要放什麼 😅  拿掉好了

2016-11-22 06:31 UTC, chuanxd requested changes

2016-11-22 06:31 UTC, chuanxd commented on src/components/dualListbox/__test__/duallistbox.spec.js
> +    //click on 3: 'ctl-jx-059-063-188-146'
please remove it

2016-11-22 06:31 UTC, CApopsicle commented on src/client/views/duallistbox/index.js
> +      console.log(data)
因為讓 `output` 顯示出來有點長＠＠

2016-11-22 06:35 UTC, CApopsicle commented on src/components/dualListbox/__test__/duallistbox.spec.js
> +    //click on 3: 'ctl-jx-059-063-188-146'
removed!

2016-11-22 06:39 UTC, chuanxd commented on src/client/views/duallistbox/doc.md
> +    type: Function
這應該不用了？

2016-11-22 06:42 UTC, chuanxd commented on src/components/dualListbox/__test__/duallistbox.spec.js
> +  //click on selectAll
QQ 漏掉一個 eslint

`"spaced-comment": [1, "always"],`

2016-11-22 06:44 UTC, CApopsicle commented on src/components/dualListbox/__test__/duallistbox.spec.js
> +  //click on selectAll
removed

2016-11-22 06:44 UTC, CApopsicle commented on src/client/views/duallistbox/doc.md
> +    type: Function
removed

2016-11-22 06:56 UTC, chuanxd commented on src/components/dualListbox/__test__/duallistbox.spec.js
> +  //click on selectAll
?? removed what?

2016-11-22 06:59 UTC, chuanxd commented on src/client/views/duallistbox/index.js
> +    }
要不要改成把資料丟到 view 上面？

2016-11-22 07:00 UTC, CApopsicle commented on src/components/dualListbox/__test__/duallistbox.spec.js
> +  //click on selectAll
remove 其中一個 `//` 😅

2016-11-22 07:09 UTC, chuanxd commented on src/components/dualListbox/__test__/duallistbox.spec.js
> +  //click on selectAll
http://eslint.org/docs/rules/comma-spacing

2016-11-22 07:25 UTC, CApopsicle commented on src/client/views/duallistbox/index.js
> +    }
我發現放到view上面有bug QQ 雖然`getDualData`有收到每次`$emit`過來的資料 但是不會每次更新view
```
data() {
    return {
      output: { 15: 'Meowth', 16: 'Abra', 17: 'Doduo', 18: 'Dodrio' }
    }
  },
  methods: {
    getDualData(data) {
      console.log(data)
      this.output = data
    }
  }
<code class={[s.code]}>
  {JSON.stringify(this.output)}
</code>
```

2016-11-22 07:27 UTC, rwu823 commented on src/client/views/duallistbox/index.js
> +    }
是指 `this.output` 不會更新嗎

2016-11-22 07:36 UTC, CApopsicle commented on src/client/views/duallistbox/index.js
> +    }
對！！

2016-11-22 08:17 UTC, rwu823 commented
列表區可點擊範圍是不是該變手指比較好

2016-11-22 08:29 UTC, CApopsicle commented
現在列表上還有selectAll和unSelectAll的icon是 `cursor: pointer` 呀 什麼意思 🤔

2016-11-22 08:30 UTC, rwu823 commented
我的意思是點擊單筆時，其實整個範圍可以點，但卻不是 `pointer` QQ

2016-11-22 08:37 UTC, CApopsicle commented on src/client/views/duallistbox/index.js
> +    }
我想到了 要重新`Vue.$set`

2016-11-22 09:13 UTC, CApopsicle commented on src/client/views/duallistbox/index.js
> +    }
修改了！

2016-11-22 09:17 UTC, rwu823 commented on src/client/views/duallistbox/index.js
> +    }
但是我 select 也一樣沒這個問題耶

2016-11-23 07:06 UTC, CApopsicle commented
新增文件上對 `onChange` 和 `$emit` 的說明

2016-11-24 07:49 UTC, rwu823 approved these changes

2016-11-24 08:09 UTC, merged