[OWL-1072] Vue.v2 <Switch> component add new style and change to use `$emit` and `onChange listener`
cepave-f2e/vue-owl-ui pull request #66
Opened 2016-11-25 03:29 UTC by CApopsicle

- `<Switch>` 的api接口改用 `$emit`和`onChange listener`
- 新增`<Switch>`樣式，可使用
```
<Switch checked={true}>
    <Switch.Open>開</Switch.Open>
    <Switch.Close>關</Switch.Close>
</Switch>
```
在Button上加字
![switch_button](https://cloud.githubusercontent.com/assets/5334755/20613713/90082c62-b301-11e6-9f4b-4f096441b8d8.gif)

ps. gif套件錄不到 `cursor: pointer`，``hover`到Switch Button上會變成`pointer`的

2016-11-25 05:56 UTC, CApopsicle commented
修改一下樣式 ＱＱ
<img width="384" alt="2016-11-25 1 56 07" src="https://cloud.githubusercontent.com/assets/5334755/20615659/f3ff92a4-b316-11e6-9e9e-c478745b3591.png">

2016-11-25 05:57 UTC, rwu823 commented
點在點上不會變灰
![switch](https://cloud.githubusercontent.com/assets/890063/20615672/29c4e81c-b330-11e6-84ea-c1ab233857b3.gif)

2016-11-25 06:00 UTC, rwu823 requested changes

2016-11-25 06:00 UTC, rwu823 commented on src/components/switch/__test__/switch.spec.js
> +it('test props `typ` and add words in switch button', () => {
這邊偷渡了QQ，怎麼沒有任何 `expect`?

2016-11-25 06:01 UTC, chuanxd commented on src/components/switch/__test__/switch.spec.js
> +it('test props `typ` and add words in switch button', () => {
QQ

2016-11-28 02:35 UTC, CApopsicle commented on src/components/switch/__test__/switch.spec.js
> +it('test props `typ` and add words in switch button', () => {
修改了ＱＱ

2016-11-28 02:46 UTC, rwu823 approved these changes

2016-11-28 02:46 UTC, merged