[OWL-1294] <Table> component
cepave-f2e/vue-owl-ui pull request #72
Opened 2016-12-05 07:12 UTC by CApopsicle

`<Table>` component  
[http://jira.cepave.com/browse/OWL-1294](url)

![2016-12-05 2 57 41](https://cloud.githubusercontent.com/assets/5334755/20876203/3cff737a-bafb-11e6-8f0c-752e00a9051e.png)

- [x] component
- [x] test specs
- [x] doc

2016-12-19 00:31 UTC, rwu823 requested changes

2016-12-19 00:31 UTC, rwu823 commented on src/components/table/index.js
> +        </tfoot>
這邊如果沒有 `feet ` 是否會output 沒意義的空 tag: `<tfoot><tr></tr></tfoot>`

2016-12-19 00:31 UTC, rwu823 commented on src/components/table/index.js
> +        </tfoot>
這邊的判斷的基本上不需要，因為空 Array `[]` 永遠都等於 `true`

2016-12-19 07:17 UTC, CApopsicle commented on src/components/table/index.js
> +        </tfoot>
已修改!

2016-12-21 07:08 UTC, rwu823 requested changes

2016-12-21 07:08 UTC, rwu823 commented on src/components/table/index.js
> +          (feet.toString()) &&
可以用 `feet.length` 判斷就好

2016-12-21 07:09 UTC, rwu823 commented
這個 table 是等寬欄位 @@?

2016-12-21 07:12 UTC, chuanxd requested changes

2016-12-21 07:12 UTC, chuanxd commented on src/components/table/grid.scss
> +.col-12 { @include grid-column(12); }
class 可以寫回圈@@

2016-12-21 07:24 UTC, chuanxd commented
@rwu823 寬度應該是從 `props: heads.width` 傳入值，對應到 class name `.col-xxx`

2016-12-22 09:34 UTC, rwu823 requested changes

2016-12-22 09:34 UTC, rwu823 commented on src/client/router.js
> +        { path: 'statictable', component: require('./views/table') },
`table`

2017-01-04 08:25 UTC, rwu823 commented
這邊記得找時間修改 QQ

2017-01-16 06:34 UTC, chuanxd commented
@@

2017-01-16 06:35 UTC, rwu823 commented
阿發現刪錯耶 QQ

2017-01-16 06:41 UTC, chuanxd commented
don't worry be happy.

2017-01-17 09:16 UTC, CApopsicle commented on src/components/table/index.js
> +          (feet.toString()) &&
fixed!

2017-01-17 09:16 UTC, CApopsicle commented on src/client/router.js
> +        { path: 'statictable', component: require('./views/table') },
fixed!

2017-01-17 09:25 UTC, CApopsicle commented
這邊欄寬的部分有點問題 
如果使用 `table-layout: fixed` table不知道為什麼不會填滿整個寬度
![2017-01-17 5 20 15](https://cloud.githubusercontent.com/assets/5334755/22014607/7a953864-dcd9-11e6-899c-e525a4a88832.png)
如果不使用，就算設定
```
td {
    overflow: hidden;
    text-overflow: ellipsis;
}
```
也沒辦法處理字串過長的問題QQ
![2017-01-17 5 21 13](https://cloud.githubusercontent.com/assets/5334755/22014630/91beb88a-dcd9-11e6-808e-882f008cd3ec.png)

2017-01-18 06:51 UTC, CApopsicle commented on src/components/table/grid.scss
> +.col-12 { @include grid-column(12); }
已拿掉 變成直接填寫
```
{ col: 'pokemon', width: '25%' },
{ col: 'chinese_name', width: '25%' },
```
跟`<Grid>`一樣

2017-01-18 06:54 UTC, CApopsicle commented on src/components/table/__test__/table.spec.js
> +  })
照理說應該也可以寫
```
expect($(vm.$el).find('[style="width:50%"]').length).toBe('8')
```
但不知道為什麼這樣的selector不會work QQ

2017-01-18 07:51 UTC, rwu823 commented
@CApopsicle 有省略 `width` 就均分的功能嗎 @@

2017-01-18 08:08 UTC, CApopsicle commented
我加一下 😅

2017-02-13 10:19 UTC, rwu823 commented
table `props` 資料結構設定請參考 ant 的，後來發現這樣比較好用: grid 也需要修改 T_T

https://ant.design/components/table/

2017-02-13 10:22 UTC, CApopsicle commented
👌

2017-02-14 09:06 UTC, CApopsicle commented
突然發現`<Table>`的資料結構跟ant的一樣耶@@ 
```
heads: [
  { col: 'pokemon', width: '25%' },
  { col: 'chinese_name', width: '25%' },
  { col: 'type', width: '25%' },
  { col: 'attack', width: '25%' }
]
rows: [
  { pokemon: 'Bulbasaur', chinese_name: '妙蛙種子', type: 'Grass Poison', attack: '35' },
  { pokemon: 'Charmander', chinese_name: '小火龍', type: 'Fire', attack: '35' },
  { pokemon: 'Squirtle', chinese_name: '傑尼龜', type: 'Water', attack: '35' },
  { pokemon: 'Pikachu', chinese_name: '皮卡丘', type: 'Electric', attack: '50' }
]
```

2017-02-23 01:40 UTC, rwu823 commented
似乎沒有自訂表頭的功能？ @@

2017-02-24 02:21 UTC, rwu823 commented
Reviewed 5 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/components/table/index.js, line 9 at r3](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/72#-KdhskSN7MslXgKCkYhC:-KdhskSN7MslXgKCkYhD:bep3r3z) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/27fdac09dbfabd6870ecfc8b13b9929f54956c0e/src/components/table/index.js#L9)):*
> ```JavaScript
>     heads: {
>       type: Array,
>       required: true
> ```

可以把 `heads` 可接受的預設的格式寫出來，方便日後維護

---

*[src/components/table/index.js, line 36 at r3](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/72#-KdhthDQ3oSwlcpmQGvJ:-KdhthDQ3oSwlcpmQGvK:beaf1yd) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/27fdac09dbfabd6870ecfc8b13b9929f54956c0e/src/components/table/index.js#L36)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>       heads.forEach((val, idx) => {
>         if (!val.width) {
>           fullAssignWidth = false
>           return
>         }
>       })
</details>

這邊是要找到任一筆 `!val.width` 就停止 loop 嗎？

---

*[src/components/table/index.js, line 74 at r3](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/72#-KdhuSgT84wfmA0oGrXJ:-KdhuSgT84wfmA0oGrXK:b-oemx3k) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/27fdac09dbfabd6870ecfc8b13b9929f54956c0e/src/components/table/index.js#L74)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>               headWidths.map((head) => {
>                 const colName = head.col.replace(/\_/g, ' ')
>                 return (
>                   <th style={`width:${head.width}`}>{colName}</th>
>                 )
>               })
</details>
loop  放進 `computed` 比較好，資料如果未更動就不用每次 render 都 loop 一次

---

*[src/components/table/index.js, line 80 at r3](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/72#-KdhudBUnxPngEOay_Qv:-KdhudBUnxPngEOay_Qw:b39knhl) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/27fdac09dbfabd6870ecfc8b13b9929f54956c0e/src/components/table/index.js#L80)):*
> ```JavaScript
>         <tbody>
>             {
>               rows.map((row) => {
> ```

loop  放進 `computed` 比較好，資料如果未更動就不用每次 render 都 loop 一次

---

*[src/components/table/index.js, line 94 at r3](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/72#-KdhufPJdAHUE_3ah-Ar:-KdhufPJdAHUE_3ah-As:b39knhl) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/27fdac09dbfabd6870ecfc8b13b9929f54956c0e/src/components/table/index.js#L94)):*
> ```JavaScript
>             <tr>
>               {
>                 feet.map((foot) => {
> ```

loop  放進 `computed` 比較好，資料如果未更動就不用每次 render 都 loop 一次

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/72)*
<!-- Sent from Reviewable.io -->

2017-06-07 09:57 UTC, closed without merging