[Tab] fix <Tab.Head> without `isSelected`
cepave-f2e/vue-owl-ui pull request #83
Opened 2016-12-09 03:45 UTC by CApopsicle

- add `border-bottom` to `<Tab.Head>`
- 如果`<Tab.Head>` 沒有加 `isSelected` ，預設select第一個

![2016-12-09 11 42 51](https://cloud.githubusercontent.com/assets/5334755/21036969/ddc4f31e-be04-11e6-8f31-91eca34202e4.png)

#80 

cc @rwu823 @chuanxd

2016-12-09 08:21 UTC, rwu823 requested changes

2016-12-09 08:21 UTC, rwu823 commented on src/components/tab/index.js
> +    }
這邊的邏輯應該是這樣寫會比較簡單，下面也不需要再改了:

```js
let selectedChild = $slots.tabHead.find((slot) => slot.child.isSelected)
if (!selectedChild) {
selectedChild = $slots.tabHead[0]
}
```

2016-12-09 08:23 UTC, CApopsicle commented on src/components/tab/index.js
> +    }
OK!

2016-12-09 08:39 UTC, CApopsicle commented on src/components/tab/index.js
> +    }
已修改！

2016-12-14 05:55 UTC, rwu823 approved these changes

2016-12-14 05:55 UTC, merged