[DualList] enhancement
cepave-f2e/vue-owl-ui pull request #84
Opened 2016-12-12 07:45 UTC by CApopsicle

- rename `DualListBox` to `DualList`
- add case insensitive search and highlight
#81 #82 

![duallistbox-2-case-insensitive](https://cloud.githubusercontent.com/assets/5334755/21091528/ba387018-c081-11e6-82fd-82825605d16e.gif)

cc @rwu823 @chuanxd

2016-12-14 06:13 UTC, rwu823 requested changes

2016-12-14 06:13 UTC, rwu823 commented on src/components/dual-list/index.js
> +      return Object.assign(preVal, { [idx]: curVal })
可以用 `...` 取代 `Object.assign`

2016-12-14 06:26 UTC, CApopsicle commented on src/components/dual-list/index.js
> +      return Object.assign(preVal, { [idx]: curVal })
👌

2016-12-14 06:28 UTC, rwu823 requested changes

2016-12-14 06:28 UTC, rwu823 commented on src/components/dual-list/index.js
>      }
如果 `Dual.List` 不需要給外部使用就不需要放在 `exports` 裡，因為只有一層外部使用也不需要 `Dual.Group`，直接:
```jsx
render(h) {
  return <DualList ...props />
}
```

2016-12-14 07:18 UTC, CApopsicle commented on src/components/dual-list/index.js
> +      return Object.assign(preVal, { [idx]: curVal })
已修改!

2016-12-14 07:18 UTC, CApopsicle commented on src/components/dual-list/index.js
>      }
已修改!

2016-12-15 06:09 UTC, rwu823 requested changes

2016-12-15 06:09 UTC, rwu823 commented on src/components/dual-list/index.js
> +        return Object.assign(preVal, { [idx]: curVal })
`Object.assign` @@

2016-12-15 06:09 UTC, rwu823 commented on src/components/dual-list/index.js
>            return Object.assign(preVal, { [curVal]: this.rightList[curVal] })
`Object.assign`

2016-12-15 06:23 UTC, rwu823 commented
發現一個 bug
![dual-bug](https://cloud.githubusercontent.com/assets/890063/21213840/2f8f5e9c-c2eb-11e6-81cc-0e97d0b8d7d9.gif)

2016-12-15 07:44 UTC, CApopsicle commented
發現第一次使用 `selectAll` and `unselectAll` 都會有資料不見問題 QQ

2016-12-15 08:54 UTC, rwu823 commented
有找到問題了嗎

2016-12-15 09:01 UTC, chuanxd commented
有找到新問題QQ

2016-12-15 09:07 UTC, CApopsicle commented
新的問題已解決ＱＱ舊的還沒ＱＱ

2016-12-19 00:15 UTC, rwu823 requested changes

2016-12-19 00:15 UTC, rwu823 commented on src/components/dual-list/index.js
> +            return this.leftList[key].toLowerCase().includes(this.$refs.searchListToAdd.value.toLowerCase())
這邊應該要根據 `props` 來決定要不要乎略大小寫

2016-12-19 00:15 UTC, rwu823 commented on src/components/dual-list/index.js
> +          return this.rightList[key].toLowerCase().includes(this.$refs.searchListToRemove.value.toLowerCase())
同上

2016-12-19 03:40 UTC, CApopsicle commented on src/components/dual-list/index.js
> +            return this.leftList[key].toLowerCase().includes(this.$refs.searchListToAdd.value.toLowerCase())
已修改！

2016-12-19 03:40 UTC, CApopsicle commented on src/components/dual-list/index.js
> +          return this.rightList[key].toLowerCase().includes(this.$refs.searchListToRemove.value.toLowerCase())
已修改！

2016-12-22 02:15 UTC, rwu823 commented
- 需要增加 custom render
- items 资料格式需改为: [{}, {}]

2016-12-22 07:32 UTC, CApopsicle commented
已修改！
- turn props `items` and `selectedItems` to `Array Object`
- add new props `displayKey`

2016-12-22 07:33 UTC, rwu823 commented
Looks great.

2016-12-22 07:33 UTC, rwu823 approved these changes

2016-12-22 07:35 UTC, merged