Vue.v2 Tip
cepave-f2e/vue-owl-ui pull request #9
Opened 2016-09-30 08:57 UTC by CApopsicle

making Tip component 
http://jira.cepave.com/browse/OWL-1082

2016-10-07 03:00 UTC, rwu823 commented on src/components/tip/__test__/tip.spec.js
> +    }, 50)
why `50ms`?

2016-10-07 03:08 UTC, rwu823 requested changes
spec 裡整體沒有 expect 到位置

2016-10-12 07:43 UTC, rwu823 approved these changes

2016-10-12 20:00 UTC, rwu823 requested changes

2016-10-12 20:00 UTC, rwu823 commented on src/components/tip/__test__/tip.spec.js
> +  vm.$el.dispatchEvent(eventEnter)
已經有引入 [cash-dom](https://github.com/kenwheeler/cash)，我們試著把這段精簡成 jQuery 的方法 trigger

2016-10-13 03:23 UTC, CApopsicle commented on src/components/tip/__test__/tip.spec.js
> +  vm.$el.dispatchEvent(eventEnter)
OK!已修改!

2016-10-13 03:25 UTC, chuanxd approved these changes

2016-10-13 03:25 UTC, chuanxd commented on src/components/tip/__test__/tip.spec.js
> +  $(vm.$el).trigger('mouseenter')
👍   變超簡潔

2016-10-19 03:08 UTC, chuanxd requested changes

2016-10-19 03:08 UTC, chuanxd commented on src/client/views/tip/index.js
> +        <Markdown src={require('./tip.md')}/>
space
`<Markdown src={require('./tip.md')} />`

2016-10-19 03:08 UTC, chuanxd commented on src/client/views/tip/tip.md
> +#Tip
follow https://guides.github.com/features/mastering-markdown/

之後會加上 markdown lint #24

2016-10-19 03:08 UTC, chuanxd commented on src/components/tip/__test__/tip.spec.js
> +    }, 50)
ping

2016-10-19 03:08 UTC, chuanxd commented on src/components/tip/__test__/tip.spec.js
> +it('test mouse event', async() => {
寫清楚會不會比較好呢？
hover event

2016-10-19 03:09 UTC, chuanxd commented
有衝突唷

2016-10-19 03:44 UTC, CApopsicle commented on src/components/tip/__test__/tip.spec.js
> +    }, 50)
之前解釋過嘍! 因為 `src/components/tip/index.js : 60`
```
setTimeout(()=> {
  _context.style.transition = 'all .4s'
  _context.style.opacity = 1
}, 50)
```

2016-10-19 06:31 UTC, CApopsicle commented
已rebase&解衝突!

2016-10-20 05:47 UTC, rwu823 approved these changes

2016-10-20 07:04 UTC, merged